/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filereader;

import java.io.File;
import java.io.IOException;

/**
 *
 * @author wgjunior
 */
public class FileReader {

    //private String diretorio = "C:\\Users\\wgjunior\\Desktop\\Eleições\\votacao_candidato_munzona";
    private String diretorio = "C:\\Users\\wgjunior\\Desktop\\Eleições\\Dados\\Resultados";
    //private String diretorio = "C:\\Users\\wgjunior\\Desktop\\Eleições\\Universo";
    
    public FileReader() throws IOException{
        File file = new File(diretorio);
        File afile[] = file.listFiles();
        int i = 0;
        for (int j = afile.length; i<j; i++){
            File arquivos = afile[i];
            System.out.println("Lendo arquivo: "+ arquivos.getName());
            
            Unzip zp = new Unzip(arquivos.getAbsoluteFile().toString());
            //readCSV rscv = new readCSV(arquivos.getAbsolutePath());
            i = j;
            
        }
        
        System.out.println("Foram listados " +i+ " arquivos." );
    
    }  
    
    
    /**
     * @param args the command line arguments
     */  
    public static void main(String[] args) {
        // TODO code application logic here
        try {
            FileReader v =  new FileReader();
        } catch (IOException e){
            e.printStackTrace();
        }
        
    }

/**
 * 
 *PERFIL_ELEITORADO_<ANO ELEIÇÃO>_<SIGLA UF>
	PERIODO 
	UF 
	MUNICIPIO 
	COD_MUNICIPIO_TSE 
	NR_ZONA 
	SEXO 
	FAIXA_ETARIA 
	GRAU_DE_ESCOLARIDADE
	QTD_ELEITORES_NO_PERFIL
------------------------------------------------------------------------------	
CONSULTA_CAND_<ANO ELEIÇÃO>_<SIGLA UF>	********************** ATÉ 2010
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	NUMERO_CANDIDATO 
	CPF_CANDIDATO 
	NOME_URNA_CANDIDATO 
	COD_SITUACAO_CANDIDATURA 
	DES_SITUACAO_CANDIDATURA 
	NUMERO_PARTIDO 
	SIGLA_PARTIDO 
	NOME_PARTIDO 
	CODIGO_LEGENDA 
	SIGLA_LEGENDA 
	COMPOSICAO_LEGENDA 
	NOME_LEGENDA 
	CODIGO_OCUPACAO 
	DESCRICAO_OCUPACAO 
	DATA_NASCIMENTO
	NUM_TITULO_ELEITORAL_CANDIDATO
	IDADE_DATA_ELEICAO
	CODIGO_SEXO 					
	DESCRICAO_SEXO 					
	COD_GRAU_INSTRUCAO
	DESCRICAO_GRAU_INSTRUCAO 		
	CODIGO_ESTADO_CIVIL 			
	DESCRICAO_ESTADO_CIVIL  		
	CODIGO_NACIONALIDADE 			
	DESCRICAO_NACIONALIDADE 		
	SIGLA_UF_NASCIMENTO 			
	CODIGO_MUNICIPIO_NASCIMENTO  	
	NOME_MUNICIPIO_NASCIMENTO 		
	DESPESA_MAX_CAMPANHA
	COD_SIT_TOT_TURNO
	DESC_SIT_TOT_TURNO
	
CONSULTA_CAND_<ANO ELEIÇÃO>_<SIGLA UF>	********************** EM 2012
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO 		
	NUM_TURNO  			
	DESCRICAO_ELEICAO  	
	SIGLA_UF  			
	SIGLA_UE
	DESCRICAO_UE   		
	CODIGO_CARGO   		
	DESCRICAO_CARGO   	
	NOME_CANDIDATO   	
	SEQUENCIAL_CANDIDATO
	NUMERO_CANDIDATO
	CPF_CANDIDATO
	NOME_URNA_CANDIDATO
	COD_SITUACAO_CANDIDATURA
	DES_SITUACAO_CANDIDATURA
	NUMERO_PARTIDO
	SIGLA_PARTIDO
	NOME_PARTIDO
	CODIGO_LEGENDA
	SIGLA_LEGENDA
	COMPOSICAO_LEGENDA
	NOME_LEGENDA
	CODIGO_OCUPACAO
	DESCRICAO_OCUPACAO
	DATA_NASCIMENTO
	NUM_TITULO_ELEITORAL_CANDIDATO
	IDADE_DATA_ELEICAO
	CODIGO_SEXO
	DESCRICAO_SEXO
	COD_GRAU_INSTRUCAO
	DESCRICAO_GRAU_INSTRUCAO
	CODIGO_ESTADO_CIVIL
	DESCRICAO_ESTADO_CIVIL
	CODIGO_NACIONALIDADE
	DESCRICAO_NACIONALIDADE
	SIGLA_UF_NASCIMENTO
	CODIGO_MUNICIPIO_NASCIMENTO
	NOME_MUNICIPIO_NASCIMENTO
	DESPESA_MAX_CAMPANHA
	COD_SIT_TOT_TURNO
	DESC_SIT_TOT_TURNO	
	
CONSULTA_CAND_<ANO ELEIÇÃO>_<SIGLA UF>	********************** EM 2012
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	DESCRICAO_UE
	CODIGO_CARGO
	DESCRICAO_CARGO
	NOME_CANDIDATO
	SEQUENCIAL_CANDIDATO
	NUMERO_CANDIDATO
	CPF_CANDIDATO
	NOME_URNA_CANDIDATO
	COD_SITUACAO_CANDIDATURA
	DES_SITUACAO_CANDIDATURA
	NUMERO_PARTIDO
	SIGLA_PARTIDO
	NOME_PARTIDO
	CODIGO_LEGENDA
	SIGLA_LEGENDA
	COMPOSICAO_LEGENDA
	NOME_LEGENDA
	CODIGO_OCUPACAO
	DESCRICAO_OCUPACAO
	DATA_NASCIMENTO
	NUM_TITULO_ELEITORAL_CANDIDATO
	IDADE_DATA_ELEICAO
	CODIGO_SEXO
	DESCRICAO_SEXO
	COD_GRAU_INSTRUCAO
	DESCRICAO_GRAU_INSTRUCAO
	CODIGO_ESTADO_CIVIL
	DESCRICAO_ESTADO_CIVIL
	CODIGO_COR_RACA
	DESCRICAO_COR_RACA
	CODIGO_NACIONALIDADE
	DESCRICAO_NACIONALIDADE
	SIGLA_UF_NASCIMENTO
	CODIGO_MUNICIPIO_NASCIMENTO
	NOME_MUNICIPIO_NASCIMENTO
	DESPESA_MAX_CAMPANHA
	COD_SIT_TOT_TURNO
	DESC_SIT_TOT_TURNO
------------------------------------------------------------------------------
BEM_CANDIDATO_<ANO ELEIÇÃO>_<SIGLA UF>	
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SQ_CANDIDATO
	CD_TIPO_BEM_CANDIDATO
	DS_TIPO_BEM_CANDIDATO
	DETALHE_BEM
	VALOR_BEM
	DATA_ULTIMA_ATUALIZACAO
	HORA_ULTIMA_ATUALIZACAO
------------------------------------------------------------------------------
CONSULTA_LEGENDAS_<ANO ELEIÇÃO>_<SIGLA UF>	
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	NOME_UE
	CODIGO_CARGO
	DESCRICAO_CARGO
	TIPO_LEGENDA
	NUM_PARTIDO
	SIGLA_PARTIDO
	NOME_PARTIDO
	SIGLA_COLIGACAO
	NOME_COLIGACAO
	COMPOSICAO_COLIGACAO
	SEQUENCIAL_COLIGACAO
------------------------------------------------------------------------------
CONSULTA_VAGAS_<ANO ELEIÇÃO>_<SIGLA UF>	
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	NOME_UE
	CODIGO_CARGO
	DESCRICAO_CARGO
	QTDE_VAGAS
------------------------------------------------------------------------------
VOTACAO_CANDIDATO_MUN_ZONA_<ANO ELEIÇÃO>_<SIGLA UF>	 ********** ATÉ 2012
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	CODIGO_MUNICIPIO
	NOME_MUNICIPIO
	NUMERO_ZONA
	CODIGO_CARGO
	NUMERO_CAND
	SQ_CANDIDATO
	NOME_CANDIDATO
	NOME_URNA_CANDIDATO
	DESCRICAO_CARGO
	COD_SIT_CAND_SUPERIOR
	DESC_SIT_CAND_SUPERIOR
	CODIGO_SIT_CANDIDATO
	DESC_SIT_CANDIDATO
	CODIGO_SIT_CAND_TOT
	DESC_SIT_CAND_TOT
	NUMERO_PARTIDO
	SIGLA_PARTIDO
	NOME_PARTIDO
	SEQUENCIAL_LEGENDA
	NOME_COLIGACAO
	COMPOSICAO_LEGENDA
	TOTAL_VOTOS
VOTACAO_CANDIDATO_MUN_ZONA_<ANO ELEIÇÃO>_<SIGLA UF>	 ********** A partir de  2014
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	CODIGO_MUNICIPIO
	NOME_MUNICIPIO
	NUMERO_ZONA
	CODIGO_CARGO
	NUMERO_CAND
	SQ_CANDIDATO
	NOME_CANDIDATO
	NOME_URNA_CANDIDATO
	DESCRICAO_CARGO
	COD_SIT_CAND_SUPERIOR
	DESC_SIT_CAND_SUPERIOR
	CODIGO_SIT_CANDIDATO
	DESC_SIT_CANDIDATO
	CODIGO_SIT_CAND_TOT
	DESC_SIT_CAND_TOT
	NUMERO_PARTIDO
	SIGLA_PARTIDO
	NOME_PARTIDO
	SEQUENCIAL_LEGENDA
	NOME_COLIGACAO
	COMPOSICAO_LEGENDA
	TOTAL_VOTOS
	TRANSITO
------------------------------------------------------------------------------
VOTACAO_PARTIDO_MUN_ZONA_<ANO ELEIÇÃO>_<SIGLA UF> ********** ATÉ 2012
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	CODIGO_MUNICIPIO
	NOME_MUNICIPIO
	NUMERO_ZONA
	CODIGO_CARGO
	DESCRICAO_CARGO
	TIPO_LEGENDA
	NOME_COLIGACAO
	COMPOSICAO_LEGENDA
	SIGLA_PARTIDO
	NUMERO_PARTIDO
	NOME_PARTIDO
	QTDE_VOTOS_NOMINAIS
	QTDE_VOTOS_LEGENDA
VOTACAO_PARTIDO_MUN_ZONA_<ANO ELEIÇÃO>_<SIGLA UF> ********** A partir de  2014
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	CODIGO_MUNICIPIO
	NOME_MUNICIPIO
	NUMERO_ZONA
	CODIGO_CARGO
	DESCRICAO_CARGO
	TIPO_LEGENDA
	NOME_COLIGACAO
	COMPOSICAO_LEGENDA
	SIGLA_PARTIDO
	NUMERO_PARTIDO
	NOME_PARTIDO
	QTDE_VOTOS_NOMINAIS
	QTDE_VOTOS_LEGENDA
	TRANSITO
------------------------------------------------------------------------------	
VOTO_SECAO_<ANO ELEIÇÃO>_<SIGLA UF>	
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	CODIGO_MUNICIPIO
	NOME_MUNICIPIO
	NUM_ZONA
	NUM_SECAO
	CODIGO_CARGO
	DESCRICAO_CARGO
	NUM_VOTAVEL
	QTDE_VOTOS
------------------------------------------------------------------------------	
DETALHE_VOTACAO_MUN_ZONA_<ANO ELEIÇÃO>_<SIGLA UF> ********** Até  2012
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	CODIGO_MUNICIPIO
	NOME_MUNICIPIO
	NUMERO_ZONA
	CODIGO_CARGO
	DESCRICAO_CARGO
	QTD_APTOS
	QTD_SECOES
	QTD_SECOES_AGREGADAS
	QTD_APTOS_TOT
	QTD_SECOES_TOT
	QTD_COMPARECIMENTO
	QTD_ABSTENCOES
	QTD_VOTOS_NOMINAIS
	QTD_VOTOS_BRANCOS
	QTD_VOTOS_NULOS
	QTD_VOTOS_LEGENDA
	QTD_VOTOS_ANULADOS_APU_SEP
	DATA_ULT_TOTALIZACAO
	HORA_ULT_TOTALIZACAO
DETALHE_VOTACAO_MUN_ZONA_<ANO ELEIÇÃO>_<SIGLA UF> ********** A partir de  2014	
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	CODIGO_MUNICIPIO
	NOME_MUNICIPIO
	NUMERO_ZONA
	CODIGO_CARGO
	DESCRICAO_CARGO
	QTD_APTOS
	QTD_SECOES
	QTD_SECOES_AGREGADAS
	QTD_APTOS_TOT
	QTD_SECOES_TOT
	QTD_COMPARECIMENTO
	QTD_ABSTENCOES
	QTD_VOTOS_NOMINAIS
	QTD_VOTOS_BRANCOS
	QTD_VOTOS_NULOS
	QTD_VOTOS_LEGENDA
	QTD_VOTOS_ANULADOS_APU_SEP
	DATA_ULT_TOTALIZACAO
	HORA_ULT_TOTALIZACAO
	TRANSITO
------------------------------------------------------------------------------
DETALHE_VOTACAO_SECAO_<ANO ELEIÇÃO>_<SIGLA UF>	
	DATA_GERACAO
	HORA_GERACAO
	ANO_ELEICAO
	NUM_TURNO
	DESCRICAO_ELEICAO
	SIGLA_UF
	SIGLA_UE
	CODIGO_MUNICIPIO
	NOME_MUNICIPIO
	NUMERO_ZONA
	NUMERO_SECAO
	CODIGO_CARGO
	DESCRICAO_CARGO
	QTD_APTOS
	QTD_COMPARECIMENTO
	QTD_ABSTENCOES
	QT_VOTOS_NOMINAIS
	QT_VOTOS_BRANCOS
	QT_VOTOS_NULOS
	QT_VOTOS_LEGENDA
	QT_VOTOS_ANULADOS_APU_SEP
 * 
 * 
 */



    
}
